apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 4
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-nginx-svc
# spec:
#   selector:
#     run: my-nginx
#   ports:
#     - port: 80
#       targetPort: 80
#   type: LoadBalancer
